### ISSUE TITLE
中文字体要大于 12px

### ISSUE THREAD

**Issue by wuliupo** [Ovilia/zhujianer#25]
刚刚看到你已经更新了代码，辛苦啦 ^_^
给个建议：从视觉角度，中文字体要大于 12px。
（对于 Chrome中文版，强制要求字体不能小于12px，对于Chrome英文版，可以看到小于12px）

比如首页（http://zhujianer.com/）最下面导航：
首页 案例 联系 团队

**Comment by Ovilia** [comment]
@wuliupo 好哒，一定改正~ 多谢多谢！:joy:
